### ISSUE TITLE
Spaced-out Formatting - Indentation with tabs?

### ISSUE THREAD

**Issue by svaisakh** [greed2411/YDL#3]
GitHub seems to render the scripts with larger than life spacing.

I suspect that indenting with spaces will fix the issue.

It's also a good practice.

**Comment by greed2411** [comment]
Lol that was because I was using sublime text during that time. I'm sure it doesn't follow the PEP8 conventions and the tabs vs spaces rule. Now I'm using vscode, I've set all tabs as 4 spaces. It's fine. I'll refactor the code soon @svaisakh
